### ISSUE TITLE
string payload wrongly converted to object

### ISSUE THREAD

**Issue by Lli0o1oIl101ILo01o0oo0OO0o1li0i0i10oil0** [cuppachino/hexgate#122]
![65912ded3d95190e2e394f7962f298db](https://github.com/cuppachino/hexgate/assets/34327084/1da10504-c48f-405c-b29b-cadac1b843b0)
![cc42ba1dcea33f0a80c167328c9bd7e0](https://github.com/cuppachino/hexgate/assets/34327084/56308af0-0d9b-47e1-af2f-8ac26a0b2c52)
![5454df1cc5ec8ed87c69e47b3cb0133b](https://github.com/cuppachino/hexgate/assets/34327084/abff5d91-8973-4441-a6dc-8b9e9d1139ff)
![e320c7df191bb3f82e6bc3d2e9552c20](https://github.com/cuppachino/hexgate/assets/34327084/c15dd55a-e64f-42a2-b6d0-9bbbdef732c7)
![dd106996835ff855b17cb3d12b11a6a7](https://github.com/cuppachino/hexgate/assets/34327084/40966152-7010-4425-b5bd-5b8d54a6c884)
![02ead070bb1844f55abb9dfdc8abc61f](https://github.com/cuppachino/hexgate/assets/34327084/32c9aec1-fddb-4a35-88f5-8eebc0e9a977)

**Comment by cuppachino** [comment]
Thanks for opening an issue. May I ask what you're trying to do? I can update the typings and/or `@cuppachino/openapi-fetch`, but its possible a v2 endpoint would suit your needs.

**Comment by cuppachino** [comment]
Looks like it's read-only anyway.

```ts
import { auth, poll, Hexgate as HttpsClient, createHeaders } from "hexgate";
import { Agent } from "https";
import fetch from "node-fetch";

// ...

const agent = new Agent({
  rejectUnauthorized: false
});

const headers = {
  "Content-Type": "application/json",
  ...createHeaders(credentials)
};

const manual = async (name: string) => {
  return fetch(
    httpsClient.baseUrl + "/lol-summoner/v1/current-summoner/name",
    {
      agent,
      headers,
      method: "POST",
      body: JSON.stringify(name)
    }
  );
};

const manual_res = await manual("dubble");
console.log(await manual_res.json());
```

![image](https://github.com/cuppachino/hexgate/assets/92656523/37624478-9ebb-48ce-b953-55085d7e50d9)

**Comment by Lli0o1oIl101ILo01o0oo0OO0o1li0i0i10oil0** [comment]
I know it's read-only; I just think it needs to be more robust in this way.

**Comment by cuppachino** [comment]
If you have the same trouble with other endpoints, open an issue or PR in https://github.com/cuppachino/openapi-typescript-fetch/tree/main. For now this isn't a huge priority because it doesn't seem to affect any *useable* endpoints.
